import { useState, useCallback } from 'react';
import { MOCK_INVOICES, formatCurrency } from './mockData';
import OfflinePayDropdown from './OfflinePayDropdown';
import ScanAndPayModal from './ScanAndPayModal';
import GenerateRefModal from './GenerateRefModal';
import SubmitPaymentModal from './SubmitPaymentModal';

const STATUS_LABELS = {
  paid: { label: 'Paid', className: 'badge-paid' },
  unpaid: { label: 'Unpaid', className: 'badge-unpaid' },
  overdue: { label: 'Overdue', className: 'badge-overdue' },
};

export default function InvoiceSearchPage() {
  const [searchForm, setSearchForm] = useState({
    invoiceId: '',
    customerName: '',
    dateFrom: '',
    dateTo: '',
    status: '',
  });
  const [results, setResults] = useState(MOCK_INVOICES);
  const [hasSearched, setHasSearched] = useState(false);

  const [scanPayInvoice, setScanPayInvoice] = useState(null);
  const [genRefInvoice, setGenRefInvoice] = useState(null);
  const [submitPayInvoice, setSubmitPayInvoice] = useState(null);

  function handleSearchChange(e) {
    const { name, value } = e.target;
    setSearchForm((prev) => ({ ...prev, [name]: value }));
  }

  function handleSearch(e) {
    e.preventDefault();
    const filtered = MOCK_INVOICES.filter((inv) => {
      const matchId = !searchForm.invoiceId || inv.id.toLowerCase().includes(searchForm.invoiceId.toLowerCase());
      const matchName = !searchForm.customerName || inv.customerName.toLowerCase().includes(searchForm.customerName.toLowerCase());
      const matchStatus = !searchForm.status || inv.status === searchForm.status;
      const matchFrom = !searchForm.dateFrom || inv.issuedDate >= searchForm.dateFrom;
      const matchTo = !searchForm.dateTo || inv.issuedDate <= searchForm.dateTo;
      return matchId && matchName && matchStatus && matchFrom && matchTo;
    });
    setResults(filtered);
    setHasSearched(true);
  }

  function handleReset() {
    setSearchForm({ invoiceId: '', customerName: '', dateFrom: '', dateTo: '', status: '' });
    setResults(MOCK_INVOICES);
    setHasSearched(false);
  }

  const handleDownloadPDF = useCallback((invoice) => {
    const printContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Invoice ${invoice.id}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
          h1 { color: #1a56db; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { padding: 10px 12px; border: 1px solid #ddd; text-align: left; }
          th { background: #f4f6f9; }
          .total { font-weight: bold; font-size: 18px; color: #1a56db; }
          .footer { margin-top: 40px; font-size: 12px; color: #888; }
        </style>
      </head>
      <body>
        <h1>VN-Payment Invoice</h1>
        <table>
          <tr><th>Invoice No.</th><td>${invoice.id}</td></tr>
          <tr><th>Customer</th><td>${invoice.customerName}</td></tr>
          <tr><th>Email</th><td>${invoice.customerEmail}</td></tr>
          <tr><th>Description</th><td>${invoice.description}</td></tr>
          <tr><th>Issued Date</th><td>${invoice.issuedDate}</td></tr>
          <tr><th>Due Date</th><td>${invoice.dueDate}</td></tr>
          <tr><th>Status</th><td>${invoice.status.toUpperCase()}</td></tr>
          <tr><th>Amount Due</th><td class="total">${formatCurrency(invoice.amount)}</td></tr>
        </table>
        <div class="footer">Generated by VN-Payment &mdash; ${new Date().toLocaleString('vi-VN')}</div>
      </body>
      </html>
    `;
    const win = window.open('', '_blank');
    win.document.write(printContent);
    win.document.close();
    win.focus();
    win.print();
  }, []);

  return (
    <div className="page">
      <header className="page-header">
        <div className="header-brand">
          <span className="brand-icon">💳</span>
          <span className="brand-name">VN-Payment</span>
        </div>
        <h1 className="page-title">Invoice Search</h1>
      </header>

      <main className="page-main">
        {/* Search Form */}
        <section className="search-card" aria-label="Invoice search form">
          <form className="search-form" onSubmit={handleSearch}>
            <div className="search-row">
              <div className="form-group">
                <label htmlFor="invoiceId">Invoice Number</label>
                <input
                  id="invoiceId"
                  name="invoiceId"
                  type="text"
                  placeholder="e.g. INV-2024-001"
                  value={searchForm.invoiceId}
                  onChange={handleSearchChange}
                />
              </div>
              <div className="form-group">
                <label htmlFor="customerName">Customer Name</label>
                <input
                  id="customerName"
                  name="customerName"
                  type="text"
                  placeholder="e.g. Nguyen Van A"
                  value={searchForm.customerName}
                  onChange={handleSearchChange}
                />
              </div>
              <div className="form-group">
                <label htmlFor="status">Status</label>
                <select id="status" name="status" value={searchForm.status} onChange={handleSearchChange}>
                  <option value="">All Statuses</option>
                  <option value="unpaid">Unpaid</option>
                  <option value="overdue">Overdue</option>
                  <option value="paid">Paid</option>
                </select>
              </div>
            </div>
            <div className="search-row">
              <div className="form-group">
                <label htmlFor="dateFrom">Issued Date From</label>
                <input
                  id="dateFrom"
                  name="dateFrom"
                  type="date"
                  value={searchForm.dateFrom}
                  onChange={handleSearchChange}
                />
              </div>
              <div className="form-group">
                <label htmlFor="dateTo">Issued Date To</label>
                <input
                  id="dateTo"
                  name="dateTo"
                  type="date"
                  value={searchForm.dateTo}
                  onChange={handleSearchChange}
                />
              </div>
              <div className="form-group form-actions">
                <button type="submit" className="btn btn-primary">
                  🔍 Search
                </button>
                <button type="button" className="btn btn-outline" onClick={handleReset}>
                  ↺ Reset
                </button>
              </div>
            </div>
          </form>
        </section>

        {/* Results Table */}
        <section className="results-card" aria-label="Invoice search results">
          <div className="results-header">
            <h2 className="results-title">
              {hasSearched ? `Search Results (${results.length})` : `All Invoices (${results.length})`}
            </h2>
          </div>

          {results.length === 0 ? (
            <div className="empty-state">
              <p>No invoices found matching your search criteria.</p>
            </div>
          ) : (
            <div className="table-wrapper">
              <table className="invoice-table">
                <thead>
                  <tr>
                    <th>Invoice No.</th>
                    <th>Customer</th>
                    <th>Description</th>
                    <th>Issued Date</th>
                    <th>Due Date</th>
                    <th>Amount</th>
                    <th>Status</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {results.map((invoice) => {
                    const status = STATUS_LABELS[invoice.status] ?? { label: invoice.status, className: '' };
                    return (
                      <tr key={invoice.id}>
                        <td className="cell-id">{invoice.id}</td>
                        <td>
                          <div className="cell-customer">
                            <span className="customer-name">{invoice.customerName}</span>
                            <span className="customer-email">{invoice.customerEmail}</span>
                          </div>
                        </td>
                        <td className="cell-description">{invoice.description}</td>
                        <td>{invoice.issuedDate}</td>
                        <td>{invoice.dueDate}</td>
                        <td className="cell-amount">{formatCurrency(invoice.amount)}</td>
                        <td>
                          <span className={`badge ${status.className}`}>{status.label}</span>
                        </td>
                        <td>
                          <div className="action-group">
                            <button
                              className="btn btn-primary btn-sm"
                              onClick={() => setScanPayInvoice(invoice)}
                              title="Scan and Pay"
                            >
                              📱 Scan &amp; Pay
                            </button>
                            <OfflinePayDropdown
                              invoice={invoice}
                              onGenerateRef={setGenRefInvoice}
                              onSubmitPayment={setSubmitPayInvoice}
                            />
                            <button
                              className="btn btn-outline btn-sm"
                              onClick={() => handleDownloadPDF(invoice)}
                              title="Download / Print Invoice PDF"
                            >
                              🖨️ Print PDF
                            </button>
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </section>
      </main>

      {/* Modals */}
      {scanPayInvoice && (
        <ScanAndPayModal invoice={scanPayInvoice} onClose={() => setScanPayInvoice(null)} />
      )}
      {genRefInvoice && (
        <GenerateRefModal invoice={genRefInvoice} onClose={() => setGenRefInvoice(null)} />
      )}
      {submitPayInvoice && (
        <SubmitPaymentModal invoice={submitPayInvoice} onClose={() => setSubmitPayInvoice(null)} />
      )}
    </div>
  );
}
